import sqlite3
from datetime import datetime

DB_NAME = "scores.db"

def init_db():
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS scores (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            module TEXT,
            score INTEGER,
            total INTEGER,
            time_taken REAL,
            timestamp TEXT,
            class_level INTEGER NOT NULL DEFAULT 4
        )
    """)
    # Existing results were all generated by the Class 4 app.
    columns = {row[1] for row in c.execute("PRAGMA table_info(scores)")}
    if "class_level" not in columns:
        c.execute("ALTER TABLE scores ADD COLUMN class_level INTEGER NOT NULL DEFAULT 4")
    conn.commit()
    conn.close()

def save_score(module, score, total, time_taken, class_level=4):
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    c.execute("""
        INSERT INTO scores (module, score, total, time_taken, timestamp, class_level)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (module, score, total, time_taken, datetime.now().strftime("%Y-%m-%d %H:%M:%S"), class_level))
    conn.commit()
    conn.close()

def get_scores():
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    c.execute("SELECT id, module, score, total, time_taken, timestamp, class_level FROM scores ORDER BY id DESC")
    rows = c.fetchall()
    conn.close()
    return rows


def clear_scores():
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    c.execute("DELETE FROM scores")
    conn.commit()
    conn.close()
